### PR TITLE
fix: add config values to hash salt

### LINKED ISSUE #552: Cache key doesn't take `--source-map` into account
## Expected Behavior
`nyc`'s cache would be invalidated when different flags are passed.

## Observed Behavior
Toggling source maps off and on doesn't have an effect; the result from whatever option was used the first time the command was run is used.

## Bonus Points! Code (or Repository) that Reproduces Issue
```sh
glimmer-perf-app :: (master*) » nyc --no-source-map node dist/app.js                                                                                                                                                                                                                ~/Code/glimmer-perf-app
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |     43.7 |     23.3 |    38.23 |    43.73 |                |
 app.js   |     43.7 |     23.3 |    38.23 |    43.73 |... 20258,20262 |
----------|----------|----------|----------|----------|----------------|


glimmer-perf-app :: (master*) » nyc --source-map node dist/app.js                                                                                                                                                                                                                   ~/Code/glimmer-perf-app
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |     43.7 |     23.3 |    38.23 |    43.73 |                |
 app.js   |     43.7 |     23.3 |    38.23 |    43.73 |... 20258,20262 |
----------|----------|----------|----------|----------|----------------|


glimmer-perf-app :: (master*) » nyc --source-map --no-cache node dist/app.js                                                                                                                                                                                                        ~/Code/glimmer-perf-app
---------------------------------------------------------------------------------------------|----------|----------|----------|----------|----------------|
File                                                                                         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------------------------------------------------------------------------------|----------|----------|----------|----------|----------------|
All files                                                                                    |    35.25 |     27.7 |    29.27 |    37.64 |                |
 Code/glimmer-perf-app/dist                                                                  |      100 |       50 |      100 |      100 |                |
  index.ts                                                                                   |      100 |       50 |      100 |      100 |                |
  main.ts                                                                                    |      100 |      100 |      100 |      100 |                |
 Code/glimmer-perf-app/dist/config                                                           |      100 |      100 |      100 |      100 |                |
  module-map.js                                                                              |      100 |      100 |      100 |      100 |                |
  resolver-configuration.js                                                                  |      100 |      100 |      100 |      100 |                |
 Code/glimmer-perf-app/dist/ui/components/glimmer-perf-app                                   |      100 |      100 |      100 |      100 |                |
  template.js                                                                                |      100 |      100 |      100 |      100 |                |
 Code/node_modules/@glimmer/component/dist/modules/es2017/src                                |    85.71 |      100 |      100 |    85.71 |                |
  component-manager.ts                                                                       |      100 |      100 |      100 |      100 |                |
...
```
## Forensic Information

**Operating System:** OS X 10.11.6
**Environment Information:** https://gist.github.com/tomdale/f572f3f94cdbe808eb0d9abfb64880e9

### PR DESCRIPTION
**Pull request by taye**
This PR adds the instrumenter-related config options to the salt of the cache hash. This fixes a bug where code that has been cached without instrumentation or source maps is incorrectly reused after the options are later enabled, leading to missing instrumentation. This problem is more likely to come up in projects using `babel-plugin-istanbul` which recommends setting the `sourceMap` and `instrument` options to `false`.

Closes #552 and probably also #822 #822 #974 #980

Thank you to everyone maintaining and contributing to this project :heart:

### CODE REVIEW

File: lib/hash.js [hunk 1]
```diff
@@ -1,8 +1,24 @@
...
+
 module.exports = {
-  salt: JSON.stringify({
-    istanbul: require('istanbul-lib-coverage/package.json').version,
-    nyc: require('../package.json').version
-  })
+  salt (config) {
+    return JSON.stringify(Object.assign(
+      {
+        istanbul: require('istanbul-lib-coverage/package.json').version,
```
Comment (coreyfarrell) [inline lib/hash.js]: I think `istanbul-lib-instrument` is needed instead of `istanbul-lib-coverage`.  `istanbul-lib-coverage` is bundled with `nyc` where `istanbul-lib-instrument` is not.  So it's impossible for you to make `nyc@13.1.0` use `istanbul-lib-coverage@2.0.3`.  It is possible to force `nyc@13.1.0` to use `istanbul-lib-instrument@3.0.1`.

I'd prefer you structure the object to be stringified as:
```js
{
  modules: {
   'istanbul-lib-instrument': require(...).version,
   nyc: require(...).version
  },
  nycrc: getInvalidatingOptions(config)
}
```

File: lib/hash.js [hunk 2]
```diff
@@ -1,8 +1,24 @@
 'use strict'
 
+function getInvalidatingOptions (config) {
+  return [
```
Comment (coreyfarrell) [inline lib/hash.js]: I think this list needs to be expanded to all configs options used in `NYC.prototype._createInstrumenter` as they all effect the output.

File: lib/hash.js [hunk 3]
```diff
@@ -1,8 +1,24 @@
...
+    'instrument',
```
Comment (coreyfarrell) [inline lib/hash.js]: I have to question - what is gained by allowing nyc to perform caching if `instrument` is disabled?  I believe babel has it's own cache so maybe caching should be disabled if `!this.config.caching || !this.config.instrument || this.config.instrumenter === 'noop'`?  Just seems like it might be wasteful at best, damaging at worst.

CC @bcoe @JaKXz thoughts?

Comment (coreyfarrell) [reply lib/hash.js]: @taye for now lets not worry about modifying the logic for disabling caching, I'll investigate that later.  Please address my other comments and we can move forward with this.

**Comment by JaKXz** [comment]
@bcoe @coreyfarrell it would be cool if all the issues @taye mentioned could actually be closed in the merge commit but I'll leave that judgement call to you

**Comment by coreyfarrell** [comment]
I think #522 is the only one this should close.  The other tickets are either unrelated or of undetermined cause.
